modLoader="javafml" #mandatory
loaderVersion="[36,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="AGPL-3.0"
[[mods]] #mandatory
modId="expanded" #mandatory
version="1.16.5-0.0.1" #mandatory
displayName="Expanded" #mandatory
logoFile="expandedLogo.png" #optional
authors="Shutdoor" #optional
description='Adds a three level pickaxe and shovel enchant that allow for mining of [3x3, 5x5, 7x7] areas.'
[[dependencies.expanded]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[36,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.expanded]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
